version: '3.3'

services:   
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'mystore'
      MYSQL_USER: 'luis'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - 3306:3306
    expose:
    - '3306'
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - PMA_HOST=mysql
    ports:
      - 8080:80